### ISSUE TITLE
Impose a horizontal width cap on charts

### ISSUE THREAD

**Issue by kschmidtDCP** [NYCPlanning/labs-migration-viz#10]
Currently, the visualization stretches according to the width of the browser window it is being viewed on. In cases when the window is much wider than it is tall, the charts become too wide for the slope of the trendline to be visible, as well as differences in vertical axis values. 

There should either be a maximum width, or preferably, a maximum aspect ratio for the charts to avoid extreme stretches.

**Comment by chriswhong** [comment]
I think a max width of 1120px is where we need to be on this.  The issue when I tried to implement it last week was that we lost alignment with the footer.  I'll try to contain it to the content area that the chart renders in

**Comment by chriswhong** [comment]
Ended up using bootstrap's built-in width for `.container` elements, which is 1170px max.  Implemented in 91b718d

**Comment by kschmidtDCP** [comment]
I think the width limit was lost in the recent updates. Can it be re-implemented?

![image](https://user-images.githubusercontent.com/20977980/34260980-95cc8784-e635-11e7-9c5a-891359bb9352.png)

**Comment by andycochran** [comment]
Fixed.
