### ISSUE TITLE
Earnings 1935-1940 shows only 4 bars

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-migration-viz#14]
Looks like we are missing some data here...

![nyc_planning_migration_viz](https://user-images.githubusercontent.com/1833820/27573143-5208d382-5ade-11e7-95cb-567a49eb7778.png)

**Comment by kschmidtDCP** [comment]
Data in 1940 were top coded at $75k, so there's no data for the last group. I made a note in the metadata about it, but could add something to the text if you think that's the best way to handle it.

**Comment by chriswhong** [comment]
I see.  Would be nice to add some visual indicator that the data is
missing, but not a high priority.

**Comment by kschmidtDCP** [comment]
Right - something like a little question mark icon over where that bar should be that tells you the data's not available for that time period and group when you click/hover on it.

**Comment by chriswhong** [comment]
Closing as `wontfix`, as this is not a priority.  Feel free to re-open if you feel strongly about this issue
