### ISSUE TITLE
Allow quick embedding in other web pages... such as NYC.gov or news article

### ISSUE THREAD

**Issue by hadekoyaDCP** [NYCPlanning/labs-migration-viz#15]

**Comment by hadekoyaDCP** [comment]
Feature to allow embedding migration visualization in other web pages... such as NYC.gov or news article

**Comment by chriswhong** [comment]
An idea for this would be to add some `iframe` code that is easily copy/pasteable...  It might also require building a stripped down version of the site that has the chart but no header and footer, or some scaled down header and footer that lends itself well to being embedded.

**Comment by hadekoyaDCP** [comment]
Not too familiar but some time not too long ago, I built Dijit (Dojo Widgets) that can be registered in web pages....Maybe that can also be of help..

**Comment by chriswhong** [comment]
Closing inactive issue, if you still want this feature, feel free to re-open this.
