### ISSUE TITLE
Add "Total" Migration Characteristic

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/labs-migration-viz#16]
Realizing we never added "Total", which would just be one single bar for each time period.  @kschmidtDCP this would be very easy to add by just adding data to the CSV, the buttons for characteristics are dynamically generated.

**Comment by kschmidtDCP** [comment]
I was thinking about this too. The data file does have a category for total, before age, but it's not being displayed. Should we just move that row to the end?
