### ISSUE TITLE
Please note if earnings are inflation adjusted

### ISSUE THREAD

**Issue by jwhong** [NYCPlanning/labs-migration-viz#19]
And if so, what year the dollar amounts are adjusted to.

**Comment by kschmidtDCP** [comment]
I can easily put this note in the Earnings blurb. However, It's a little clumsy there and may look best up with the earnings title: 
![image](https://user-images.githubusercontent.com/20977980/31189686-f24eca60-a906-11e7-94b3-6c6ca967fffe.png)
 I know that would require changing the actual code, but don't have a good idea of how time-consuming that would be. What do you think?
