### ISSUE TITLE
ZAP Login Issues

### ISSUE THREAD

**Issue by allthesignals** [NYCPlanning/labs-migration-viz#38]
Some users reporting login issues for certain browsers/OS's, but not all.

**Comment by allthesignals** [comment]
Pushed up several commits addressing a "blank" token cookie.

Still, for some reason, the login doesn't work for certain browsers.

**Comment by hannahkates** [comment]
Issue moved to [NYCPlanning/labs-zap-search #1211](https://github.com/NYCPlanning/labs-zap-search/issues/1211) via [**ZenHub**](https://www.zenhub.com/)
