### ISSUE TITLE
Reorder occupation classes

### ISSUE THREAD

**Issue by kschmidtDCP** [NYCPlanning/labs-migration-viz#7]
The current occupation list is:
_management in business, science, and arts
education, training, and library
arts, design, entertainment, sports, and media
other business, science, and arts professionals
sales and related
service occupations
office and administrative support
construction, maintenance, production, and transportation_
It should be reordered so that _service occupations_ and _office and administrative support_ are swapped. This is because office occupations should all be clustered at the beginning, and the remaining two non-office occupations should be grouped at the end.

**Comment by chriswhong** [comment]
![nyc_planning_migration_viz_](https://user-images.githubusercontent.com/1833820/27542769-43605b3a-5a56-11e7-958d-00968b7c511c.png)

Implemented in 70dfa31
