### ISSUE TITLE
Remove trendline between 1935-40 and 1975-80

### ISSUE THREAD

**Issue by kschmidtDCP** [NYCPlanning/labs-migration-viz#9]
From Joe: The current trendline connects data for all charts, beginning with 1935-40 and ending in 2010-14. In order to emphasize the break in time between the 1935-40 and 1975-80 periods, and since those periods aren't directly comparable, shorten the trendline so that it starts at 1975-80 and only connects through 2010-14.

**Comment by chriswhong** [comment]
This is easy to accomplish, but I wonder if it would be more or less confusing to add a visual break in the trendline, similar to what is proposed in #5.  

For the short-term, I will remove it, but will keep this issue open for future discussion about the best solution to the "non-continuous timeline" problem.

**Comment by kschmidtDCP** [comment]
Sounds good. Joe and I will continue thinking about this.

**Comment by chriswhong** [comment]
Added code in 91b718d to slice off the first value in the array of year range strings, limiting the data that gets created for charts.
